#!/bin/bash
# Safe Clutter Cleanup - Move unused files to _archive/ directory
# Created: October 9, 2025
# Run this, test the site, then delete _archive/ if everything works

set -e  # Exit on error

ARCHIVE_DIR="_archive/$(date +%Y%m%d_%H%M%S)"
echo "📦 Creating archive directory: $ARCHIVE_DIR"
mkdir -p "$ARCHIVE_DIR"

# Function to safely move files
safe_move() {
    local file="$1"
    if [ -f "$file" ] || [ -d "$file" ]; then
        echo "  Moving: $file"
        mkdir -p "$ARCHIVE_DIR/$(dirname "$file")"
        mv "$file" "$ARCHIVE_DIR/$file"
    fi
}

echo ""
echo "🗑️  PHASE 1: Injury System Test Files (20 files)"
safe_move "test-injury-simple.js"
safe_move "test-injury-fix.js"
safe_move "test-injury-calculations.js"
safe_move "test-injury-calculations-fixed.js"
safe_move "test-injury-game-picks-integration.js"
safe_move "test-injury-game-picks-integration-fixed.js"
safe_move "test-injury-integration-proof.js"
safe_move "test-injury-integration-final.js"
safe_move "test-injury-system-local.js"
safe_move "test-injury-timeout.js"
safe_move "test-live-injury-debug.js"
safe_move "safe-injury-debug.js"
safe_move "test-current-injuries-2025.js"
safe_move "manual-week5-injury-test.js"
safe_move "week5-injury-debug.js"

echo ""
echo "🗑️  PHASE 2: Debug Scripts (20 files)"
safe_move "debug-injury-structure.R"
safe_move "debug-json-structure.R"
safe_move "debug-injury-integration-detailed.js"
safe_move "debug-injury-system-comprehensive.js"
safe_move "debug-universal-injury-impact.js"
safe_move "debug-mnf-injury-impact.js"
safe_move "debug-nabers-injury-impact.js"
safe_move "mnf-injury-debug.js"
safe_move "analyze-injury-impact.js"
safe_move "browser-debug-injury-impact.js"
safe_move "debug-market-odds.js"
safe_move "debug-model-analysis.js"
safe_move "debug-nfl-td-data.js"
safe_move "debug-nfl-td-odds.js"
safe_move "web-console-injury-debug.js"
safe_move "web-console-injury-debug-v2.js"
safe_move "web-console-injury-debug-v3.js"
safe_move "web-console-injury-impact-only.js"
safe_move "unbiased-web-console-test.js"
safe_move "test-blank-page-debug.js"

echo ""
echo "🗑️  PHASE 3: Elite/QB Test Files (10 files)"
safe_move "test-elite-injury-system.js"
safe_move "test-elite-v2-system.js"
safe_move "test-elite-injury-sf-tb.js"
safe_move "test-qb-injury-cascade.js"
safe_move "test-qb-change-detector.js"
safe_move "test-qb-lookup.js"
safe_move "test-jayden-daniels-specifically.js"
safe_move "test-jayden-specifically.js"
safe_move "test-joe-burrow-fix.js"
safe_move "elite-qb-injury-cascade.js"

echo ""
echo "🗑️  PHASE 4: Other Test Files (15 files)"
safe_move "test-canonical-availability-system.js"
safe_move "test-canonical-availability-bulletproof.js"
safe_move "test-safeguards-v4-1.js"
safe_move "test-residual-decay-system.js"
safe_move "test-rookie-qb-projections.js"
safe_move "test-kelly-hybrid-staking.js"
safe_move "test-kelly-units.js"
safe_move "test-devig-implementation.js"
safe_move "test-baseline-correction.js"
safe_move "test-td-function.js"
safe_move "test-soccer-fix.js"
safe_move "test-soccer-team-stats.js"
safe_move "test-syntax.js"
safe_move "test-env-vars.js"
safe_move "simple-api-test.js"

echo ""
echo "🗑️  PHASE 5: Deployment/Integration Scripts (5 files)"
safe_move "deploy-comprehensive-injury-system.js"
safe_move "netlify-injury-integration.js"
safe_move "comprehensive-injury-system-v3.js"
safe_move "enhanced-injury-replacement-system.js"
safe_move "nfl-game-picks-generator.cjs"

echo ""
echo "🗑️  PHASE 6: R Export Scripts (7 files)"
safe_move "convert_for_react.R"
safe_move "direct_export.R"
safe_move "export_features.R"
safe_move "final_export.R"
safe_move "minimal_export.R"
safe_move "examine_cache.R"
safe_move "test-cloud-pipeline.R"

echo ""
echo "🗑️  PHASE 7: Outdated Docs (15 files)"
safe_move "CANONICAL_AVAILABILITY_V5_PRODUCTION_READY.md"
safe_move "CANONICAL_AVAILABILITY_V5_PRODUCTION_READY_FINAL.md"
safe_move "ELITE_INJURY_SYSTEM_AUDIT.md"
safe_move "INJURY_INTEGRATION_SUMMARY.md"
safe_move "INTEGRATION_COMPLETE_SUMMARY.md"
safe_move "PHASE1_IMPLEMENTATION_SUMMARY.md"
safe_move "PHASE1_QUICK_START.md"
safe_move "QUICK_START_TESTING_GUIDE.md"
safe_move "TEST_INJURY_SYSTEM.md"
safe_move "GPT_FEEDBACK_IMPLEMENTATION_SUMMARY.md"
safe_move "GPT_FIXES_IMPLEMENTATION_SUMMARY.md"
safe_move "FINAL_POLISH_IMPLEMENTATION_SUMMARY.md"
safe_move "CACHE_FIRST_ARCHITECTURE_SUMMARY.md"
safe_move "DEBUG_LIVE_ANALYSIS.md"
safe_move "INJURY_DEPTH_CHART_INTEGRATION_ANALYSIS.md"
safe_move "injury-architecture-analysis.md"

echo ""
echo "🗑️  PHASE 8: Old CSV Exports & Data (13 files)"
safe_move "nfl-week3-advanced-top-150-anytime-td.csv"
safe_move "nfl-week3-advanced-top-30-first-td.csv"
safe_move "nfl-week3-advanced-top-50-multiple-td.csv"
safe_move "nfl-week3-top-150-anytime-td.csv"
safe_move "nfl-week3-top-30-first-td.csv"
safe_move "nfl-week3-top-50-multiple-td.csv"
safe_move "nfl-week4-game-picks-2025-09-26T18-59-53.csv"
safe_move "NFL-Week4-Subscriber-Picks-2025-09-26T19-06-27.csv"
safe_move "NFL-Week4-Subscriber-Picks-2025-09-26T19-08-46.csv"
safe_move "generate-advanced-td-csv-exports.js"
safe_move "test-sgp-output.json"
safe_move "test-injury-data.json"
safe_move "backtest-config.json"

echo ""
echo "🗑️  PHASE 9: Zip Archives (3 files)"
safe_move "NFL-Elite-Injury-System-v4.1-Safeguarded-Complete-20250930.zip"
safe_move "NFL-Elite-Injury-System-v4.1-Safeguarded-Production-20250930.zip"
safe_move "nfl-td-enhanced-system.zip"

echo ""
echo "🗑️  PHASE 10: Misc Root Files (3 files)"
safe_move "update-depth-charts.js"
safe_move "reformat-depth-chart.js"
safe_move "safe-cleanup.js"
safe_move "nfl-train.js"
safe_move "MLB.jsx"
safe_move "="

echo ""
echo "🗑️  PHASE 11: Redundant Directories"
safe_move "enhanced-epa-system"
safe_move "enhanced-epa-system-staging"
safe_move "nfl-predictions-generate"
safe_move "balldontlie-injury-patch"
safe_move "_export_injury_patch"
safe_move "etlify"

echo ""
echo "✅ CLEANUP COMPLETE!"
echo ""
echo "📊 Archive created at: $ARCHIVE_DIR"
echo ""
echo "🧪 NEXT STEPS:"
echo "1. Test your site thoroughly (all models should work)"
echo "2. Check Netlify deployment succeeds"
echo "3. If everything works, delete the archive:"
echo "   rm -rf $ARCHIVE_DIR"
echo ""
echo "🔄 TO RESTORE (if something breaks):"
echo "   cp -r $ARCHIVE_DIR/* ."
echo ""
