[build]
  command = "node ./scripts/prebuild-install-react.mjs && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

# Keep your SPA routing working
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
