[build]
  # Run a safe prebuild checker, then a verbose Vite build via a Node wrapper
  command = "npm install --no-audit --no-fund && npm run prebuild && node ./scripts/run-vite-build.mjs"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  # Turn on Vite internal debug logs
  DEBUG = "vite:*"
  # Ensure CI verbosity
  CI = "true"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
