[build]
  command = "bash netlify/build-debug.sh || echo 'no build script, deploying functions only'"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]
