[build]
  command = "npm ci && npm run prebuild && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
