[build]
  # Force visibility into what's failing:
  command = "node ./scripts/print-env.mjs && npm install --no-audit --no-fund --loglevel verbose && npm run prebuild && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
