[build]
command = ""
publish = "dist"

[functions]
directory = "netlify/functions_live_ball"
node_bundler = "esbuild"
external_node_modules = []
included_files = []

[build.environment]
NODE_VERSION = "18"
