[build]
  # Use npm install (works without package-lock.json). If you add a lockfile later,
  # you can revert to `npm ci` for reproducible builds.
  command = "npm install --no-audit --no-fund && npm run prebuild && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
