[build]
  command = "npm install --no-audit --no-fund && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

# Keep your SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
