# Netlify config for Round Robin Odds (NFL + MLB)
# Enforce Node 20 to satisfy 'round-robin-odds-free@1.4.3' (engine >=20)
[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  # Optional: speed up installs and avoid audit/fund noise
  NPM_FLAGS = "--no-audit --no-fund"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
