[build]
command = "npm run build"
publish = "dist"

[functions]
directory = "netlify/functions_live_ball"
node_bundler = "esbuild"
external_node_modules = []
included_files = []

[build.environment]
NODE_VERSION = "18"
# If your project needs a specific pnpm/yarn, uncomment:
# NPM_FLAGS = "--legacy-peer-deps"
