#!/usr/bin/env python3
"""
Generate Bundesliga BTTS predictions cache for CI/CD.

This script is designed to run in GitHub Actions (or locally) to:
1. Fetch upcoming Bundesliga fixtures + odds
2. Run the full ensemble prediction pipeline
3. Write results to data/bundesliga/cache/bundesliga_btts_latest.json

The cache is then committed and deployed, allowing the Netlify function
to serve pre-generated predictions without spawning Python at runtime.

Usage:
    python scripts/soccer/generate_bundesliga_btts_cache.py

Environment:
    ODDS_API_KEY: Optional - The Odds API key for live odds (fallback to CSV if not set)
"""

from __future__ import annotations

import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

# Add scripts/soccer to path so we can import the core module
sys.path.insert(0, str(Path(__file__).parent))

from bundesliga_btts_core import (
    CACHE_DIR,
    fetch_upcoming_fixtures,
    load_models,
    run_bundesliga_btts,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)


def main() -> None:
    """Generate and save Bundesliga BTTS cache."""
    logger.info("=" * 60)
    logger.info("Bundesliga BTTS Cache Generator")
    logger.info("=" * 60)

    # Ensure cache directory exists
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    logger.info("Cache directory: %s", CACHE_DIR)

    # Load models once
    logger.info("Loading models...")
    try:
        models = load_models()
        logger.info("✓ Models loaded successfully")
    except Exception as exc:
        logger.error("✗ Failed to load models: %s", exc)
        sys.exit(1)

    # Fetch fixtures
    logger.info("Fetching upcoming fixtures...")
    try:
        fixtures = fetch_upcoming_fixtures(limit=20)
        logger.info("✓ Found %d fixtures", len(fixtures))
        
        if not fixtures:
            logger.warning("No fixtures available - generating empty cache")
    except Exception as exc:
        logger.error("✗ Failed to fetch fixtures: %s", exc)
        sys.exit(1)

    # Run predictions
    logger.info("Running ensemble predictions...")
    generated_at = datetime.now(timezone.utc)
    
    try:
        result = run_bundesliga_btts(
            fixtures,
            models=models,
            generated_at=generated_at,
        )
        logger.info("✓ Generated %d predictions", result["total_predictions"])
        logger.info("✓ Found %d recommended bets", result["recommended_bets"])
    except Exception as exc:
        logger.error("✗ Prediction pipeline failed: %s", exc)
        sys.exit(1)

    # Add metadata for frontend
    cache_output = {
        **result,
        "league": "Bundesliga",
        "source": result["model"],
        "cache_version": "1.0",
        "note": (
            "Bundesliga BTTS predictions are pre-generated by CI. "
            "Odds may be slightly stale but predictions are fresh."
        ),
    }

    # Write to cache file
    cache_file = CACHE_DIR / "bundesliga_btts_latest.json"
    logger.info("Writing cache to %s...", cache_file)
    
    try:
        with cache_file.open("w", encoding="utf-8") as f:
            json.dump(cache_output, f, indent=2, ensure_ascii=False)
        logger.info("✓ Cache written successfully")
    except Exception as exc:
        logger.error("✗ Failed to write cache: %s", exc)
        sys.exit(1)

    # Print summary
    logger.info("=" * 60)
    logger.info("Cache Generation Summary")
    logger.info("=" * 60)
    logger.info("Generated at:        %s", cache_output["generated_at"])
    logger.info("Total predictions:   %d", cache_output["total_predictions"])
    logger.info("Recommended bets:    %d", cache_output["recommended_bets"])
    logger.info("Validation ROI:      %.1f%%", cache_output["validation_roi"] * 100)
    logger.info("Hit rate:            %.1f%%", cache_output["hit_rate"] * 100)
    logger.info("Cache file:          %s", cache_file)
    logger.info("Cache size:          %.1f KB", cache_file.stat().st_size / 1024)
    logger.info("=" * 60)
    
    if cache_output["recommended_bets"] > 0:
        logger.info("\nRecommended bets:")
        for bet in cache_output.get("bets", [])[:5]:  # Show first 5
            logger.info(
                "  • %s vs %s (edge: %.1f%%, odds: %.2f)",
                bet["home_team"],
                bet["away_team"],
                bet["edge"] * 100,
                bet["market_odds"]["btts_yes"],
            )
        if len(cache_output.get("bets", [])) > 5:
            logger.info("  ... and %d more", len(cache_output["bets"]) - 5)
    
    logger.info("\n✓ Cache generation complete!")


if __name__ == "__main__":
    main()
