/**
 * SSOT LOADER - Single Source of Truth for NFL Receiving Props
 * 
 * Loads pre-computed player parameters from JSON generated by R script.
 * Applies game-specific multipliers with soft clipping to prevent explosions.
 * 
 * Features:
 * - Opponent defense adjustments (ADOT bucket-specific)
 * - Weather modifiers (wind/precipitation)
 * - Injury impact (additive delta, not multiplicative)
 * - Snap percentage scaling
 * - Soft clipping (±7% per factor, ±12% combined) via tanh
 * 
 * FIXED: Beta mean-shifting (v1.1) - now properly shifts catch rate mean, not just concentration
 */

import fs from 'fs/promises';

/**
 * Load SSOT JSON for a given week/season
 * Uses import.meta.url for portable path resolution in bundled functions
 */
export async function loadSSOT(week, season = 2025) {
  // Allow override via env var (for CI/containers)
  const candidate = process.env.SSOT_DIR
    ? `${process.env.SSOT_DIR}/week_${week}_${season}.json`
    : new URL(
        `../../../data/nfl/ssot/week_${week}_${season}.json`,
        import.meta.url
      ).pathname;
  
  console.log(`[SSOT Loader] Attempting to load from: ${candidate}`);
  console.log(`[SSOT Loader] SSOT_DIR env var: ${process.env.SSOT_DIR || 'not set'}`);
  console.log(`[SSOT Loader] import.meta.url: ${import.meta.url}`);
  
  try {
    const data = await fs.readFile(candidate, 'utf8');
    const ssot = JSON.parse(data);
    
    // Validate schema version
    if (ssot.schema_version !== 1) {
      throw new Error(`Unsupported SSOT schema version: ${ssot.schema_version}`);
    }
    
    console.log(`✅ Loaded SSOT: Week ${ssot.week}, ${ssot.players.length} players, generated ${ssot.generated_at}`);
    
    return ssot;
  } catch (error) {
    console.warn(`⚠️  Could not load SSOT: ${error.message}`);
    return null;
  }
}

/**
 * Soft clip using tanh-based limiter
 * Prevents multiplier explosions while preserving gradient
 */
function softClip(value, min, max) {
  const mid = (max + min) / 2;
  const range = (max - min) / 2;
  
  // Normalize to [-1, 1] range
  const normalized = (value - mid) / range;
  
  // Apply tanh for soft saturation
  const clipped = Math.tanh(normalized);
  
  // Denormalize back to [min, max]
  return mid + clipped * range;
}

/**
 * Compose and cap multipliers
 * 
 * Order: opponent → weather → injury → snap_pct
 * Each factor capped individually, then combined cap applied
 */
export function composeModifiers(mods, caps) {
  const {
    opp = {},
    weather = {},
    injury = {},
    snap_pct = {}
  } = mods;
  
  const { combined_min = 0.88, combined_max = 1.12 } = caps;
  
  // Individual factors (already capped in SSOT generation)
  const oppFactor = {
    targets: opp.targets_pct || 1.0,
    catch: opp.catch_pct || 1.0,
    yac: opp.yac_pct || 1.0
  };
  
  const weatherFactor = {
    catch: weather.catch_pct || 1.0,
    cap: weather.cap || 1.0
  };
  
  const injuryFactor = {
    targets_delta: injury.targets_delta || 0,
    uncertainty: injury.uncertainty || 0
  };
  
  const snapFactor = snap_pct.projected || 1.0;
  
  // Compose multiplicatively
  const rawTargetsMult = oppFactor.targets * snapFactor;
  const rawCatchMult = oppFactor.catch * weatherFactor.catch;
  const rawYacMult = oppFactor.yac * weatherFactor.cap;
  
  // Apply soft clip to combined multipliers
  const targetsMult = softClip(rawTargetsMult, combined_min, combined_max);
  const catchMult = softClip(rawCatchMult, combined_min, combined_max);
  const yacMult = softClip(rawYacMult, combined_min, combined_max);
  
  return {
    targets: {
      multiplier: targetsMult,
      delta: injuryFactor.targets_delta,
      raw: rawTargetsMult
    },
    catchRate: {
      multiplier: catchMult,
      raw: rawCatchMult
    },
    yac: {
      multiplier: yacMult,
      raw: rawYacMult
    },
    uncertainty: injuryFactor.uncertainty,
    clipped: {
      targets: Math.abs(targetsMult - rawTargetsMult) > 0.001,
      catchRate: Math.abs(catchMult - rawCatchMult) > 0.001,
      yac: Math.abs(yacMult - rawYacMult) > 0.001
    }
  };
}

/**
 * Apply modifiers to SSOT parameters
 * Returns adjusted parameters ready for simulation
 */
export function applyModifiers(player, modifiers) {
  const { neg_bin, beta, lognorm } = player;
  const { targets, catchRate, yac, uncertainty } = modifiers;
  
  // 1. Targets (Negative Binomial)
  const adjustedMu = (neg_bin.mu * targets.multiplier) + targets.delta;
  
  // Inflate variance if injury uncertainty present
  const uncertaintyMult = 1 + uncertainty;
  const adjustedPhi = neg_bin.phi * uncertaintyMult;
  
  // 3. Catch rate (Beta-Binomial) - FIXED: Now shifts MEAN via logit, not just concentration
  const eps = 1e-6;
  const mu = beta.alpha / (beta.alpha + beta.beta); // current mean
  const nu = Math.max(beta.alpha + beta.beta, 2); // concentration (min 2 for valid beta)
  
  // Multiplicative mean shift with logit cap (prevents going outside [0,1])
  const muPrime = Math.min(0.99, Math.max(0.01, mu * catchRate.multiplier));
  
  // Reconstruct alpha/beta from shifted mean and original concentration
  const adjustedAlpha = muPrime * nu;
  const adjustedBeta = (1 - muPrime) * nu;
  
  // 3. Yards per catch (Lognormal) - shift log mean, inflate sigma
  const adjustedLogMu = lognorm.log_mu + Math.log(yac.multiplier);
  const adjustedLogSigma = lognorm.log_sigma * uncertaintyMult;
  
  // 4. NaN guards (defensive - prevent poisoning simulator)
  const clean = x => (Number.isFinite(x) ? x : 0);
  
  return {
    playerId: player.player_id,
    gameDate: player.context?.game_date || new Date().toISOString(),
    
    // Targets (Negative Binomial)
    meanTargets: clean(adjustedMu),
    kTargets: clean(adjustedPhi > 0 ? adjustedMu / adjustedPhi : adjustedMu), // k = mu / phi
    
    // Catches (Beta-Binomial)
    alphaCatch: clean(adjustedAlpha),
    betaCatch: clean(adjustedBeta),
    
    // Yards per catch (Lognormal)
    yardsPerCatchMu: clean(adjustedLogMu),
    yardsPerCatchSigma: Math.max(clean(adjustedLogSigma), 1e-6), // ensure positive
    
    // Metadata for logging
    modifiers: {
      targets_mult: targets.multiplier,
      targets_delta: targets.delta,
      catch_mult: catchRate.multiplier,
      yac_mult: yac.multiplier,
      uncertainty: uncertainty,
      clipped: modifiers.clipped
    }
  };
}

/**
 * Convert SSOT player to simulation parameters
 * Main entry point for scanner
 */
export function playerToParams(player) {
  const modifiers = composeModifiers(player.mods || {}, player.caps || {});
  return applyModifiers(player, modifiers);
}
